services:
  - type: web
    name: instagram-viewer
    runtime: node
    region: oregon
    plan: free
    buildCommand: rm -rf node_modules package-lock.json && npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: PORT
        value: 3000
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
